# Generated by Django 2.2 on 2019-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='counter',
            field=models.IntegerField(default=5),
        ),
    ]
